version: '3.8'

services:
  hadoop:
    build: .
    image: hadoop-image
    container_name: hadoop-container
    ports:
      - "50070:50070"
      - "8088:8088"
      - "9000:9000"
    volumes:
      - ./src/WordCount.java:/usr/local/hadoop/my-java-files/WordCount.java
      - ./src/input.txt:/usr/local/hadoop/my-data/input.txt
      - ./src/compile-java.sh:/usr/local/hadoop/my-script/compile-java.sh
    environment:
      - HDFS_NAMENODE_USER=root
      - HDFS_DATANODE_USER=root
      - HDFS_SECONDARYNAMENODE_USER=root
      - YARN_RESOURCEMANAGER_USER=root
      - YARN_NODEMANAGER_USER=root
      - JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
    hostname: localhost
    networks:
      - hadoop_network

networks:
  hadoop_network:
    driver: bridge